/**
 * API エラー型定義
 */

/**
 * APIエラーレスポンス
 */
export interface ApiError {
  statusCode: number
  statusMessage?: string
  message: string
  code?: string
  details?: unknown
}

/**
 * エラーコード定数
 */
export const ERROR_CODES = {
  // 認証・認可エラー (401, 403)
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // バリデーションエラー (400)
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_PARAMETER: 'MISSING_PARAMETER',
  INVALID_PARAMETER: 'INVALID_PARAMETER',
  INVALID_FILE_NAME: 'INVALID_FILE_NAME',
  INVALID_PATH: 'INVALID_PATH',
  INVALID_FOLDER_NAME: 'INVALID_FOLDER_NAME',

  // リソースエラー (404, 409)
  NOT_FOUND: 'NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  FOLDER_ALREADY_EXISTS: 'FOLDER_ALREADY_EXISTS',

  // ファイルアップロードエラー (413, 415)
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  INVALID_MIME_TYPE: 'INVALID_MIME_TYPE',

  // サーバーエラー (500)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  STORAGE_ERROR: 'STORAGE_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
